### ISSUE TITLE
Pasting doesn't work correctly with multiple tabs

### ISSUE THREAD

**Issue by RonNabuurs** [bigbn/drop-down-terminal-x#14]
When having multiple tabs open and I paste text with `ctrl+shift+v`, the text gets  paste into (want seems to be) the last terminal tab. Only when using right click and paste with mouse the pasting works correctly

**Comment by TheMesoria** [comment]
Hi!

I was able to reproduce it, and found more issues – sometimes when you copy, It happens to copy only 'o', for some reason.

**Comment by ericdallo** [comment]
same problem of @ronneke1996 , when paste,the text goes to the last tab... but `right click -> paste` does not work well in some editors like `vim`. Please @bigbn  fix the `Ctrl+shift+v`

**Comment by Shaltz** [comment]
Hi all, 
I still encounter this issue on a daily basis... 
I don't know if the facts that I have multiple tabs open
is a factor but it makes DDTX pretty much useless after about 1 hour of work...
I m on ubuntu 20.04 and I only face this issue when using vim (plain ol' vim, no plugins, themes or what not...)
The only workaround that I ve found is to call up nano instead of vim... quite annoying

issue is there whether I use ctrl + shift + v or middle mouse button

some one has an idea ?


EDIT: 

It seems that holding Shift while pasting with the middle mouse button does the trick.... weird....
why ? dunno...

**Comment by bigbn** [comment]
Why don't you just use the system-wide `shift+insert`? I'm not an author of the original extension and don't really know why does it need special copy-paste overloads. I use DDTX regularly and got no suitable situations to use them.
