### ISSUE TITLE
still capture key bindings when not focused

### ISSUE THREAD

**Issue by jakio6** [bigbn/drop-down-terminal-x#30]
drop down terminal will capture keybinds for size changing when even when it was not on the drop down state

**Comment by snaggen** [comment]
This fix really only fixes half of the problem. By default you capture Alt+LeftArrow to move between tabs. This fix seems to avoid acting on the keypresses when not focused. However, you have till stolen Alt+LeftArrow globally, so no other application will ever see that key-press. And since Alt+LeftArrow is used as Back in numerous applications, this is BAD!
I suggest you register/deregister the keyboard shortcuts when the window is shown/hidden, to avoid stealing all keypresses. You should only need to have one global shortcut registered to show/hide the window.
