### ISSUE TITLE
"gjs not found in PATH" despite gjs being found in by command line shell

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [bigbn/drop-down-terminal-x#44]
I have installed _drop-down-terminal-x_ via the _gnome-shell-extension-drop-down-terminal-x_ package in Arch Linux. Trying to run it results in the following notification:
> Drop down terminal failed to start 
Cause: gjs not found in PATH

But entering `$ gjs` finds and runs gjs.

**Comment by bigbn** [comment]
Oh, this is already fixed in 837da3388b1142aeb23efa078a903f6bf4ba3288, but I did't know that somebody made package in aur. I'l try to contact maintaner, to automate his work if it possible, because there might be some lag between changes.
Now i'm just added new version tag, so when the package in aur changes version, this updates will be available

**Comment by bigbn** [comment]
@k0ste призываю тебя!) Надо автоматизировать выпуск в aur, ну и спасибо, тебе конечно.

**Comment by k0ste** [comment]
@bigbn для каждого пакета есть кнопочка "Flag package out-of-date".

**Comment by ChristophSchmidpeter** [comment]
@bigbn and @k0ste: Thank you! Now it works
