### ISSUE TITLE
exiting bash should close the terminal

### ISSUE THREAD

**Issue by hferreiro** [bigbn/drop-down-terminal-x#52]
When executing `exit` or pressing `ctrl+d`, the terminal should close. Instead, all text is cleared and a new prompt is shown.

**Comment by bigbn** [comment]
You see it because previous terminal is closed and new has appeared. This is default behaviour and I won't change it. You can make your fork if you want, I only can show the place where it can be switched in code.

https://github.com/bigbn/drop-down-terminal-x/blob/master/drop-down-terminal-x%40bigbn.pro/terminal.js#L544

**Comment by hferreiro** [comment]
Just one more comment to try to change your mind: this would be consistent with the current behaviour when multiple tabs are opened, and with the behavior of most (all?) Linux terminal emulators.
