### ISSUE TITLE
Add GNOME 40 support, please! And add it to https://extensions.gnome.org/extension/1509/drop-down-terminal-x/

### ISSUE THREAD

**Issue by zefkerr** [bigbn/drop-down-terminal-x#94]
The extension does not work on GNOME 40.

**Comment by bigbn** [comment]
Has something broken, or just version upgrade is needed?

**Comment by zefkerr** [comment]
> Has something broken, or just version upgrade is needed?

An innovation since GNOME 40 is that any extension cannot be enabled unless the current version of GNOME is listed in the list of supported versions. Therefore, I can not even just turn it on to check if everything works.

**Comment by bigbn** [comment]
Found necessary information, will port as soon as possible.

https://blogs.gnome.org/shell-dev/2021/03/20/extensions-rebooted-porting-your-existing-extensions-to-gnome-40/
https://gjs.guide/extensions/upgrading/gnome-shell-40.html

**Comment by bigbn** [comment]
Take a look at: https://github.com/amezin/gnome-shell-extension-ddterm
I think @amezin made a best solution for us. It is much better, cleaner and polished. Has every preferences you want. I think what this is a new generation and should replace legacy extensions like this. I do not plan to compete with him. So I'm going to drop support of this extension an switch to `ddterm` by myself.
So I recommend to use `ddterm`. Just because it really cool and even works on wayland.
You will like it. Thanks for everybody and now just please support him.

**Comment by zefkerr** [comment]
> Take a look at: https://github.com/amezin/gnome-shell-extension-ddterm
> I think @amezin made a best solution for us. It is much better, cleaner and polished. Has every preferences you want. I think what this is a new generation and should replace legacy extensions like this. I do not plan to compete with him. So I'm going to drop support of this extension an switch to `ddterm` by myself.
> So I recommend to use `ddterm`. Just because it really cool and even works on wayland.
> You will like it. Thanks for everybody and now just please support him.

Thank you!
